### ISSUE TITLE
bootstrap.py imports from nonexistent pip module 'util'

### ISSUE THREAD

**Issue by csghormley** [VOLTTRON/openeis#6]
The bootstrap module attempts to import from pip.util which doesn't exist. 

     def get_dist(name):
     -    from pip.util import get_installed_distributions
     +    from pip.utils import get_installed_distributions

**Comment by hashstat** [comment]
In September, the pip team replaced the pip.util module with the pip.utils package. That change must have appeared in a recent release. In November, we modified bootstrap.py on the master branch and it no longer imports pip.util. I just pulled that change into the 1.x branch and this issue should be fixed. Thanks for the report.
